// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: order.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EcommerceServiceClient is the client API for EcommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcommerceServiceClient interface {
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	GetOrderItems(ctx context.Context, in *GetOrderItemsRequest, opts ...grpc.CallOption) (EcommerceService_GetOrderItemsClient, error)
}

type ecommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcommerceServiceClient(cc grpc.ClientConnInterface) EcommerceServiceClient {
	return &ecommerceServiceClient{cc}
}

func (c *ecommerceServiceClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, "/orderpb.EcommerceService/placeOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) GetOrderItems(ctx context.Context, in *GetOrderItemsRequest, opts ...grpc.CallOption) (EcommerceService_GetOrderItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EcommerceService_ServiceDesc.Streams[0], "/orderpb.EcommerceService/getOrderItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &ecommerceServiceGetOrderItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EcommerceService_GetOrderItemsClient interface {
	Recv() (*GetOrderItemResponse, error)
	grpc.ClientStream
}

type ecommerceServiceGetOrderItemsClient struct {
	grpc.ClientStream
}

func (x *ecommerceServiceGetOrderItemsClient) Recv() (*GetOrderItemResponse, error) {
	m := new(GetOrderItemResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EcommerceServiceServer is the server API for EcommerceService service.
// All implementations must embed UnimplementedEcommerceServiceServer
// for forward compatibility
type EcommerceServiceServer interface {
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	GetOrderItems(*GetOrderItemsRequest, EcommerceService_GetOrderItemsServer) error
	mustEmbedUnimplementedEcommerceServiceServer()
}

// UnimplementedEcommerceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEcommerceServiceServer struct {
}

func (UnimplementedEcommerceServiceServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedEcommerceServiceServer) GetOrderItems(*GetOrderItemsRequest, EcommerceService_GetOrderItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOrderItems not implemented")
}
func (UnimplementedEcommerceServiceServer) mustEmbedUnimplementedEcommerceServiceServer() {}

// UnsafeEcommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcommerceServiceServer will
// result in compilation errors.
type UnsafeEcommerceServiceServer interface {
	mustEmbedUnimplementedEcommerceServiceServer()
}

func RegisterEcommerceServiceServer(s grpc.ServiceRegistrar, srv EcommerceServiceServer) {
	s.RegisterService(&EcommerceService_ServiceDesc, srv)
}

func _EcommerceService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderpb.EcommerceService/placeOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_GetOrderItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetOrderItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EcommerceServiceServer).GetOrderItems(m, &ecommerceServiceGetOrderItemsServer{stream})
}

type EcommerceService_GetOrderItemsServer interface {
	Send(*GetOrderItemResponse) error
	grpc.ServerStream
}

type ecommerceServiceGetOrderItemsServer struct {
	grpc.ServerStream
}

func (x *ecommerceServiceGetOrderItemsServer) Send(m *GetOrderItemResponse) error {
	return x.ServerStream.SendMsg(m)
}

// EcommerceService_ServiceDesc is the grpc.ServiceDesc for EcommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderpb.EcommerceService",
	HandlerType: (*EcommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "placeOrder",
			Handler:    _EcommerceService_PlaceOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getOrderItems",
			Handler:       _EcommerceService_GetOrderItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order.proto",
}
